; /etc/php/8.5/fpm/pool.d/nis-rcis.conf
[nis-rcis]
user = nis-rcis
group = nis-rcis
listen = /run/php/php8.5-fpm-nis-rcis.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 20
pm.start_servers = 4
pm.min_spare_servers = 2
pm.max_spare_servers = 6
pm.max_requests = 500

php_admin_value[upload_max_filesize] = 10M
php_admin_value[post_max_size] = 12M
php_admin_value[memory_limit] = 256M
php_admin_value[expose_php] = Off
php_admin_value[session.cookie_secure] = 1
php_admin_flag[display_errors] = off
